name: Update M3U8 Streams

on:
  schedule:
    - cron: "*/2 * * * *"  # runs every 2 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  update-streams:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4. Ensure data folder exists (for first run)
      - name: Ensure data folder
        run: mkdir -p data

      # 5. Run the Python script and capture link count
      - name: Run update script
        id: update
        run: |
          LINK_COUNT=$(python update_streams_json.py | grep 'link_count=' | cut -d'=' -f2)
          echo "link_count=$LINK_COUNT" >> $GITHUB_OUTPUT

      # 6. Commit and push changes
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/streams.json

          # If streams.json is new or changed, commit and push
          git diff --cached --quiet || \
          (git commit -m "Auto-update streams.json ($LINK_COUNT links)" && git push)
        env:
          LINK_COUNT: ${{ steps.update.outputs.link_count }}
